### ISSUE TITLE
docker tutorial - container build error

### ISSUE THREAD

**Issue by diffcunha** [dockerlisbon/1st-meetup#1]
não conseguir correr o tutorial de docker
quando tento fazer build tenho o erro:

$ docker build -t test-app .
Uploading context 3.117 MB
Uploading context 
Step 0 : FROM dockerfile/nodejs
Pulling repository dockerfile/nodejs
ec3f14b7134c: Download complete 
27cf78414709: Download complete 
b750fe79269d: Download complete 
d85d887f973e: Download complete 
777d184a1643: Download complete 
f9bc51d0ff19: Download complete 
39af521ad98a: Download complete 
436d790902ea: Download complete 
df89b7d55e9c: Download complete 
fc24a5ffd90d: Download complete 
1967e71cf0a7: Download complete 
f3cffea87017: Download complete 
efd2358fd6e4: Download complete 
550a793d99f2: Download complete 
f67efa717962: Download complete 
ea2a97fa2de9: Download complete 
fc24bbfb9d86: Download complete 
 ---> ec3f14b7134c
Step 1 : ADD . /src
2014/02/06 21:38:16 build: Forbidden path outside the build context: . (/mnt/sda1/tmp/docker-build447558646)

**Comment by soarez** [comment]
Tanto eu como o @tdantas e o @jdduarte tivemos exactamente o mesmo problema.

Só consegui criar containers fazendo skip do `ADD`. Segundo o @apocas deve estar relacionado com a imagem do boot2docker. instalei o docker num ubuntu normalmente e funcionou tudo bem. 

Relacionado: [dotclout/docker#3980](https://github.com/dotcloud/docker/issues/3980)

**Comment by diffcunha** [comment]
Thanks @Soarez, o @joaojeronimo disse-me ontem que tinhas resolvido.

**Comment by apocas** [comment]
https://github.com/steeve/boot2docker/commit/f79b052d5aecabf0d2ef07ab72b7b9679fecebce

It seems fixed :+1:
